//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backend.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Line {0} is empty.
        /// </summary>
        internal static string FileStructureBusinessContract_LineIsEmpty {
            get {
                return ResourceManager.GetString("FileStructureBusinessContract_LineIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a File structure is invalid, see log: | {0}.
        /// </summary>
        internal static string FileStructureBusinessContract_Message {
            get {
                return ResourceManager.GetString("FileStructureBusinessContract_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Property {0} was no informed at line {1}.
        /// </summary>
        internal static string FileStructureBusinessContract_ValueIsNotNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("FileStructureBusinessContract_ValueIsNotNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Property {0} must be a date valid at line {1}.
        /// </summary>
        internal static string FileStructureBusinessContract_ValueMustBeDateTime {
            get {
                return ResourceManager.GetString("FileStructureBusinessContract_ValueMustBeDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Property {0} must be a decimal number valid at line {1}.
        /// </summary>
        internal static string FileStructureBusinessContract_ValueMustBeDouble {
            get {
                return ResourceManager.GetString("FileStructureBusinessContract_ValueMustBeDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Property {0} must be an integer number valid at line {1}.
        /// </summary>
        internal static string FileStructureBusinessContract_ValueMustBeInteger {
            get {
                return ResourceManager.GetString("FileStructureBusinessContract_ValueMustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Property {0} was no informed at line {1}.
        /// </summary>
        internal static string FileStructureBusinessContract_ValueNoInformed {
            get {
                return ResourceManager.GetString("FileStructureBusinessContract_ValueNoInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Date must be valid at line {0}.
        /// </summary>
        internal static string FinancialTransactionBusinessContract_DateMustBeValid {
            get {
                return ResourceManager.GetString("FinancialTransactionBusinessContract_DateMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Financial Transaction Type is required at line {0}.
        /// </summary>
        internal static string FinancialTransactionBusinessContract_FinancialTransactionTypeIsRequired {
            get {
                return ResourceManager.GetString("FinancialTransactionBusinessContract_FinancialTransactionTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product is required at line {0}.
        /// </summary>
        internal static string FinancialTransactionBusinessContract_ProductIsRequired {
            get {
                return ResourceManager.GetString("FinancialTransactionBusinessContract_ProductIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seller is required at line {0}.
        /// </summary>
        internal static string FinancialTransactionBusinessContract_SellerIsRequired {
            get {
                return ResourceManager.GetString("FinancialTransactionBusinessContract_SellerIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Value must be greater than zero at line {0}.
        /// </summary>
        internal static string FinancialTransactionBusinessContract_ValueMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("FinancialTransactionBusinessContract_ValueMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Content Type is required.
        /// </summary>
        internal static string FinancialTransactionImportFileViewModelContract_ContentTypeIsRequired {
            get {
                return ResourceManager.GetString("FinancialTransactionImportFileViewModelContract_ContentTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a File is required.
        /// </summary>
        internal static string FinancialTransactionImportFileViewModelContract_FileIsRequired {
            get {
                return ResourceManager.GetString("FinancialTransactionImportFileViewModelContract_FileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a File must be a text file.
        /// </summary>
        internal static string FinancialTransactionImportFileViewModelContract_FileMustBeTextFile {
            get {
                return ResourceManager.GetString("FinancialTransactionImportFileViewModelContract_FileMustBeTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email or password are incorrect.
        /// </summary>
        internal static string SignInService_EmailAndPasswordAreIncorrect {
            get {
                return ResourceManager.GetString("SignInService_EmailAndPasswordAreIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sign in not allowed.
        /// </summary>
        internal static string SignInService_UserIsNotAllowed {
            get {
                return ResourceManager.GetString("SignInService_UserIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User temporarily blocked for invalid attempt.
        /// </summary>
        internal static string SignInService_UserIstemporarilyBlocked {
            get {
                return ResourceManager.GetString("SignInService_UserIstemporarilyBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The field e-mail is invalid.
        /// </summary>
        internal static string SignInViewModelContract_EmailIsInvalid {
            get {
                return ResourceManager.GetString("SignInViewModelContract_EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The field e-mail is required.
        /// </summary>
        internal static string SignInViewModelContract_EmailIsRequired {
            get {
                return ResourceManager.GetString("SignInViewModelContract_EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The field password is required.
        /// </summary>
        internal static string SignInViewModelContract_PasswordIsRequired {
            get {
                return ResourceManager.GetString("SignInViewModelContract_PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A password must have between 6 a 15 characters.
        /// </summary>
        internal static string SignInViewModelContract_PasswordMustHaveBetween_6_15_characteres {
            get {
                return ResourceManager.GetString("SignInViewModelContract_PasswordMustHaveBetween_6_15_characteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The field e-mail is invalid.
        /// </summary>
        internal static string UserViewModelContract_EmailIsInvalid {
            get {
                return ResourceManager.GetString("UserViewModelContract_EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The field e-mail is required.
        /// </summary>
        internal static string UserViewModelContract_EmailIsRequired {
            get {
                return ResourceManager.GetString("UserViewModelContract_EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The field password is required.
        /// </summary>
        internal static string UserViewModelContract_PasswordIsRequired {
            get {
                return ResourceManager.GetString("UserViewModelContract_PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A password must have between 6 a 15 characters.
        /// </summary>
        internal static string UserViewModelContract_PasswordMustHaveBetween_6_15_characteres {
            get {
                return ResourceManager.GetString("UserViewModelContract_PasswordMustHaveBetween_6_15_characteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The passwords are different.
        /// </summary>
        internal static string UserViewModelContract_PasswordsAreDifferent {
            get {
                return ResourceManager.GetString("UserViewModelContract_PasswordsAreDifferent", resourceCulture);
            }
        }
    }
}
